import type { IDigimon } from "../typings/digimon"

export const testDigimons: IDigimon[] = [
  {
    id: 349,
    name: "V-mon",
    xAntibody: false,
    images: [{ href: "https://digi-api.com/images/digimon/w/V-mon.png", transparent: false }],
    levels: [{ id: 4, level: "Child" }],
    types: [{ id: 80, type: "Small Dragon" }],
    attributes: [{ id: 2, attribute: "Free" }, { id: 4, attribute: "Vaccine" }],
    fields: [{ id: 5, field: "Dragon's Roar", image: "https://digi-api.com/images/etc/fields/Dragon's_Roar.png" }],
    releaseDate: "2000",
    descriptions: [],
    skills: [],
    priorEvolutions: [],
    nextEvolutions: [],
  },
  {
    id: 83,
    name: "Tailmon",
    xAntibody: false,
    images: [{ href: "https://digi-api.com/images/digimon/w/Tailmon.png", transparent: false }],
    levels: [{ id: 4, level: "Child" }],
    types: [{ id: 50, type: "Beast" }],
    attributes: [{ id: 1, attribute: "Data" }],
    fields: [{ id: 1, field: "Metal Empire", image: "https://digi-api.com/images/etc/fields/Metal_Empire.png" }],
    releaseDate: "1999",
    descriptions: [],
    skills: [],
    priorEvolutions: [],
    nextEvolutions: [],
  },
  {
    id: 9,
    name: "Gigimon",
    xAntibody: false,
    images: [{ href: "https://digi-api.com/images/digimon/w/Gigimon.png", transparent: false }],
    levels: [{ id: 3, level: "In-Training" }],
    types: [{ id: 20, type: "Beast" }],
    attributes: [{ id: 2, attribute: "Free" }],
    fields: [{ id: 9, field: "Virus Busters", image: "https://digi-api.com/images/etc/fields/Virus_Busters.png" }],
    releaseDate: "2001",
    descriptions: [],
    skills: [],
    priorEvolutions: [],
    nextEvolutions: [],
  },
  {
    id: 2,
    name: "Airdramon",
    xAntibody: false,
    images: [{ href: "https://digi-api.com/images/digimon/w/Airdramon.png", transparent: false }],
    levels: [{ id: 5, level: "Adult" }],
    types: [{ id: 70, type: "Dragon" }],
    attributes: [{ id: 4, attribute: "Vaccine" }],
    fields: [{ id: 7, field: "Wind Guardians", image: "https://digi-api.com/images/etc/fields/Wind_Guardians.png" }],
    releaseDate: "2002",
    descriptions: [],
    skills: [],
    priorEvolutions: [],
    nextEvolutions: [],
  },
  {
    id: 3,
    name: "Angemon",
    xAntibody: false,
    images: [{ href: "https://digi-api.com/images/digimon/w/Angemon.png", transparent: false }],
    levels: [{ id: 6, level: "Adult" }],
    types: [{ id: 60, type: "Angel" }],
    attributes: [{ id: 4, attribute: "Vaccine" }],
    fields: [{ id: 1, field: "Metal Empire", image: "https://digi-api.com/images/etc/fields/Metal_Empire.png" }],
    releaseDate: "1998",
    descriptions: [],
    skills: [],
    priorEvolutions: [],
    nextEvolutions: [],
  },
  {
    id: 18,
    name: "Meramon",
    xAntibody: false,
    images: [{ href: "https://digi-api.com/images/digimon/w/Meramon.png", transparent: false }],
    levels: [{ id: 5, level: "Adult" }],
    types: [{ id: 10, type: "Flame" }],
    attributes: [{ id: 4, attribute: "Vaccine" }],
    fields: [{ id: 5, field: "Dragon's Roar", image: "https://digi-api.com/images/etc/fields/Dragon's_Roar.png" }],
    releaseDate: "2001",
    descriptions: [],
    skills: [],
    priorEvolutions: [],
    nextEvolutions: [],
  },
  {
    id: 22,
    name: "Numemon",
    xAntibody: false,
    images: [{ href: "https://digi-api.com/images/digimon/w/Numemon.png", transparent: false }],
    levels: [{ id: 4, level: "Child" }],
    types: [{ id: 50, type: "Beast" }],
    attributes: [{ id: 3, attribute: "Virus" }],
    fields: [{ id: 4, field: "Unknown", image: "https://digi-api.com/images/etc/fields/Unknown.png" }],
    releaseDate: "1997",
    descriptions: [],
    skills: [],
    priorEvolutions: [],
    nextEvolutions: [],
  },
  {
    id: 25,
    name: "Tyranomon",
    xAntibody: false,
    images: [{ href: "https://digi-api.com/images/digimon/w/Tyranomon.png", transparent: false }],
    levels: [{ id: 6, level: "Adult" }],
    types: [{ id: 30, type: "Dinosaur" }],
    attributes: [{ id: 2, attribute: "Free" }],
    fields: [{ id: 2, field: "Nature Spirits", image: "https://digi-api.com/images/etc/fields/Nature_Spirits.png" }],
    releaseDate: "2003",
    descriptions: [],
    skills: [],
    priorEvolutions: [],
    nextEvolutions: [],
  },
  {
    id: 31,
    name: "Seadramon",
    xAntibody: false,
    images: [{ href: "https://digi-api.com/images/digimon/w/Seadramon.png", transparent: false }],
    levels: [{ id: 5, level: "Adult" }],
    types: [{ id: 40, type: "Sea Dragon" }],
    attributes: [{ id: 3, attribute: "Virus" }],
    fields: [{ id: 9, field: "Virus Busters", image: "https://digi-api.com/images/etc/fields/Virus_Busters.png" }],
    releaseDate: "2004",
    descriptions: [],
    skills: [],
    priorEvolutions: [],
    nextEvolutions: [],
  },
  {
    id: 34,
    name: "Greymon",
    xAntibody: false,
    images: [{ href: "https://digi-api.com/images/digimon/w/Greymon.png", transparent: false }],
    levels: [{ id: 6, level: "Adult" }],
    types: [{ id: 80, type: "Small Dragon" }],
    attributes: [{ id: 2, attribute: "Free" }],
    fields: [{ id: 5, field: "Dragon's Roar", image: "https://digi-api.com/images/etc/fields/Dragon's_Roar.png" }],
    releaseDate: "1999",
    descriptions: [],
    skills: [],
    priorEvolutions: [],
    nextEvolutions: [],
  },
  {
    id: 35,
    name: "Kabuterimon",
    xAntibody: false,
    images: [{ href: "https://digi-api.com/images/digimon/w/Kabuterimon.png", transparent: false }],
    levels: [{ id: 6, level: "Adult" }],
    types: [{ id: 50, type: "Beast" }],
    attributes: [{ id: 1, attribute: "Data" }],
    fields: [{ id: 7, field: "Wind Guardians", image: "https://digi-api.com/images/etc/fields/Wind_Guardians.png" }],
    releaseDate: "2000",
    descriptions: [],
    skills: [],
    priorEvolutions: [],
    nextEvolutions: [],
  },
  {
    id: 43,
    name: "Centalmon",
    xAntibody: false,
    images: [{ href: "https://digi-api.com/images/digimon/w/Centalmon.png", transparent: false }],
    levels: [{ id: 7, level: "Perfect" }],
    types: [{ id: 90, type: "Holy Knight" }],
    attributes: [{ id: 4, attribute: "Vaccine" }],
    fields: [{ id: 1, field: "Metal Empire", image: "https://digi-api.com/images/etc/fields/Metal_Empire.png" }],
    releaseDate: "2005",
    descriptions: [],
    skills: [],
    priorEvolutions: [],
    nextEvolutions: [],
  },
  {
    id: 48,
    name: "Dark Tyranomon",
    xAntibody: false,
    images: [{ href: "https://digi-api.com/images/digimon/w/Dark_Tyranomon.png", transparent: false }],
    levels: [{ id: 7, level: "Perfect" }],
    types: [{ id: 30, type: "Dinosaur" }],
    attributes: [{ id: 3, attribute: "Virus" }],
    fields: [{ id: 4, field: "Unknown", image: "https://digi-api.com/images/etc/fields/Unknown.png" }],
    releaseDate: "2003",
    descriptions: [],
    skills: [],
    priorEvolutions: [],
    nextEvolutions: [],
  },
  {
    id: 50,
    name: "Devidramon",
    xAntibody: false,
    images: [{ href: "https://digi-api.com/images/digimon/w/Devidramon.png", transparent: false }],
    levels: [{ id: 7, level: "Perfect" }],
    types: [{ id: 10, type: "Flame" }],
    attributes: [{ id: 2, attribute: "Free" }],
    fields: [{ id: 5, field: "Dragon's Roar", image: "https://digi-api.com/images/etc/fields/Dragon's_Roar.png" }],
    releaseDate: "2004",
    descriptions: [],
    skills: [],
    priorEvolutions: [],
    nextEvolutions: [],
  },
  {
    id: 73,
    name: "Monochromon",
    xAntibody: false,
    images: [{ href: "https://digi-api.com/images/digimon/w/Monochromon.png", transparent: false }],
    levels: [{ id: 6, level: "Adult" }],
    types: [{ id: 55, type: "Machine" }],
    attributes: [{ id: 4, attribute: "Vaccine" }],
    fields: [{ id: 6, field: "Machine Empire", image: "https://digi-api.com/images/etc/fields/Machine_Empire.png" }],
    releaseDate: "2002",
    descriptions: [],
    skills: [],
    priorEvolutions: [],
    nextEvolutions: [],
  },
  {
    id: 78,
    name: "Orgemon",
    xAntibody: false,
    images: [{ href: "https://digi-api.com/images/digimon/w/Orgemon.png", transparent: false }],
    levels: [{ id: 7, level: "Perfect" }],
    types: [{ id: 90, type: "Holy Knight" }],
    attributes: [{ id: 4, attribute: "Vaccine" }],
    fields: [{ id: 1, field: "Metal Empire", image: "https://digi-api.com/images/etc/fields/Metal_Empire.png" }],
    releaseDate: "2006",
    descriptions: [],
    skills: [],
    priorEvolutions: [],
    nextEvolutions: [],
  },
  {
    id: 83,
    name: "Tailmon",
    xAntibody: false,
    images: [{ href: "https://digi-api.com/images/digimon/w/Tailmon.png", transparent: false }],
    levels: [{ id: 4, level: "Child" }],
    types: [{ id: 50, type: "Beast" }],
    attributes: [{ id: 1, attribute: "Data" }],
    fields: [{ id: 1, field: "Metal Empire", image: "https://digi-api.com/images/etc/fields/Metal_Empire.png" }],
    releaseDate: "1999",
    descriptions: [],
    skills: [],
    priorEvolutions: [],
    nextEvolutions: [],
  },
  {
    id: 1,
    name: "Agumon",
    xAntibody: false,
    images: [{ href: "https://digi-api.com/images/digimon/w/Agumon.png", transparent: false }],
    levels: [{ id: 3, level: "Rookie" }],
    types: [{ id: 10, type: "Dragon" }],
    attributes: [{ id: 1, attribute: "Data" }],
    fields: [{ id: 2, field: "Dragon Empire", image: "https://digi-api.com/images/etc/fields/Dragon_Empire.png" }],
    releaseDate: "1999",
    descriptions: [],
    skills: [],
    priorEvolutions: [],
    nextEvolutions: [],
  },
  {
    id: 2,
    name: "Gabumon",
    xAntibody: false,
    images: [{ href: "https://digi-api.com/images/digimon/w/Gabumon.png", transparent: false }],
    levels: [{ id: 3, level: "Rookie" }],
    types: [{ id: 12, type: "Beast" }],
    attributes: [{ id: 1, attribute: "Data" }],
    fields: [{ id: 3, field: "Beast Empire", image: "https://digi-api.com/images/etc/fields/Beast_Empire.png" }],
    releaseDate: "1999",
    descriptions: [],
    skills: [],
    priorEvolutions: [],
    nextEvolutions: [],
  },
  {
    id: 3,
    name: "Angemon",
    xAntibody: false,
    images: [{ href: "https://digi-api.com/images/digimon/w/Angemon.png", transparent: false }],
    levels: [{ id: 3, level: "Rookie" }],
    types: [{ id: 14, type: "Bird" }],
    attributes: [{ id: 1, attribute: "Data" }],
    fields: [{ id: 4, field: "Sky Empire", image: "https://digi-api.com/images/etc/fields/Sky_Empire.png" }],
    releaseDate: "1999",
    descriptions: [],
    skills: [],
    priorEvolutions: [],
    nextEvolutions: [],
  },
  {
    id: 4,
    name: "Tentomon",
    xAntibody: false,
    images: [{ href: "https://digi-api.com/images/digimon/w/Tentomon.png", transparent: false }],
    levels: [{ id: 3, level: "Rookie" }],
    types: [{ id: 15, type: "Insect" }],
    attributes: [{ id: 1, attribute: "Data" }],
    fields: [{ id: 5, field: "Insect Empire", image: "https://digi-api.com/images/etc/fields/Insect_Empire.png" }],
    releaseDate: "1999",
    descriptions: [],
    skills: [],
    priorEvolutions: [],
    nextEvolutions: [],
  },
  {
    id: 5,
    name: "Palmon",
    xAntibody: false,
    images: [{ href: "https://digi-api.com/images/digimon/w/Palmon.png", transparent: false }],
    levels: [{ id: 3, level: "Rookie" }],
    types: [{ id: 16, type: "Plant" }],
    attributes: [{ id: 1, attribute: "Data" }],
    fields: [{ id: 6, field: "Plant Empire", image: "https://digi-api.com/images/etc/fields/Plant_Empire.png" }],
    releaseDate: "1999",
    descriptions: [],
    skills: [],
    priorEvolutions: [],
    nextEvolutions: [],
  },
  {
    id: 6,
    name: "Gomamon",
    xAntibody: false,
    images: [{ href: "https://digi-api.com/images/digimon/w/Gomamon.png", transparent: false }],
    levels: [{ id: 3, level: "Rookie" }],
    types: [{ id: 17, type: "Sea Animal" }],
    attributes: [{ id: 1, attribute: "Data" }],
    fields: [{ id: 7, field: "Sea Empire", image: "https://digi-api.com/images/etc/fields/Sea_Empire.png" }],
    releaseDate: "1999",
    descriptions: [],
    skills: [],
    priorEvolutions: [],
    nextEvolutions: [],
  },
  {
    id: 7,
    name: "Patamon",
    xAntibody: false,
    images: [{ href: "https://digi-api.com/images/digimon/w/Patamon.png", transparent: false }],
    levels: [{ id: 3, level: "Rookie" }],
    types: [{ id: 18, type: "Mammal" }],
    attributes: [{ id: 1, attribute: "Data" }],
    fields: [{ id: 8, field: "Sky Empire", image: "https://digi-api.com/images/etc/fields/Sky_Empire.png" }],
    releaseDate: "1999",
    descriptions: [],
    skills: [],
    priorEvolutions: [],
    nextEvolutions: [],
  },
  {
    id: 8,
    name: "Gatomon",
    xAntibody: false,
    images: [{ href: "https://digi-api.com/images/digimon/w/Gatomon.png", transparent: false }],
    levels: [{ id: 4, level: "Champion" }],
    types: [{ id: 19, type: "Beast" }],
    attributes: [{ id: 1, attribute: "Data" }],
    fields: [{ id: 1, field: "Metal Empire", image: "https://digi-api.com/images/etc/fields/Metal_Empire.png" }],
    releaseDate: "1999",
    descriptions: [],
    skills: [],
    priorEvolutions: [],
    nextEvolutions: [],
  },
  {
    id: 9,
    name: "Veemon",
    xAntibody: false,
    images: [{ href: "https://digi-api.com/images/digimon/w/Veemon.png", transparent: false }],
    levels: [{ id: 3, level: "Rookie" }],
    types: [{ id: 10, type: "Dragon" }],
    attributes: [{ id: 1, attribute: "Data" }],
    fields: [{ id: 2, field: "Dragon Empire", image: "https://digi-api.com/images/etc/fields/Dragon_Empire.png" }],
    releaseDate: "2000",
    descriptions: [],
    skills: [],
    priorEvolutions: [],
    nextEvolutions: [],
  },
  {
    id: 10,
    name: "Wormmon",
    xAntibody: false,
    images: [{ href: "https://digi-api.com/images/digimon/w/Wormmon.png", transparent: false }],
    levels: [{ id: 3, level: "Rookie" }],
    types: [{ id: 15, type: "Insect" }],
    attributes: [{ id: 1, attribute: "Data" }],
    fields: [{ id: 5, field: "Insect Empire", image: "https://digi-api.com/images/etc/fields/Insect_Empire.png" }],
    releaseDate: "2000",
    descriptions: [],
    skills: [],
    priorEvolutions: [],
    nextEvolutions: [],
  },
  {
    id: 11,
    name: "Hawkmon",
    xAntibody: false,
    images: [{ href: "https://digi-api.com/images/digimon/w/Hawkmon.png", transparent: false }],
    levels: [{ id: 3, level: "Rookie" }],
    types: [{ id: 14, type: "Bird" }],
    attributes: [{ id: 1, attribute: "Data" }],
    fields: [{ id: 4, field: "Sky Empire", image: "https://digi-api.com/images/etc/fields/Sky_Empire.png" }],
    releaseDate: "2000",
    descriptions: [],
    skills: [],
    priorEvolutions: [],
    nextEvolutions: [],
  },
  {
    id: 12,
    name: "Armadillomon",
    xAntibody: false,
    images: [{ href: "https://digi-api.com/images/digimon/w/Armadillomon.png", transparent: false }],
    levels: [{ id: 3, level: "Rookie" }],
    types: [{ id: 20, type: "Reptile" }],
    attributes: [{ id: 1, attribute: "Data" }],
    fields: [{ id: 9, field: "Reptile Empire", image: "https://digi-api.com/images/etc/fields/Reptile_Empire.png" }],
    releaseDate: "2000",
    descriptions: [],
    skills: [],
    priorEvolutions: [],
    nextEvolutions: [],
  },
  {
    id: 13,
    name: "Patamon X",
    xAntibody: true,
    images: [{ href: "https://digi-api.com/images/digimon/w/Patamon_X.png", transparent: false }],
    levels: [{ id: 5, level: "Ultimate" }],
    types: [{ id: 18, type: "Mammal" }],
    attributes: [{ id: 1, attribute: "Vaccine" }],
    fields: [{ id: 8, field: "Sky Empire", image: "https://digi-api.com/images/etc/fields/Sky_Empire.png" }],
    releaseDate: "2001",
    descriptions: [],
    skills: [],
    priorEvolutions: [],
    nextEvolutions: [],
  },
  {
    id: 14,
    name: "Gatomon X",
    xAntibody: true,
    images: [{ href: "https://digi-api.com/images/digimon/w/Shoeshoemon.png", transparent: false }],
    levels: [{ id: 5, level: "Ultimate" }],
    types: [{ id: 19, type: "Beast" }],
    attributes: [{ id: 1, attribute: "Vaccine" }],
    fields: [{ id: 1, field: "Metal Empire", image: "https://digi-api.com/images/etc/fields/Metal_Empire.png" }],
    releaseDate: "2001",
    descriptions: [],
    skills: [],
    priorEvolutions: [],
    nextEvolutions: [],
  },
  {
    id: 15,
    name: "Gabumon X",
    xAntibody: true,
    images: [{ href: "https://digi-api.com/images/digimon/w/Grand_Galemon.png", transparent: false }],
    levels: [{ id: 5, level: "Ultimate" }],
    types: [{ id: 12, type: "Beast" }],
    attributes: [{ id: 1, attribute: "Vaccine" }],
    fields: [{ id: 3, field: "Beast Empire", image: "https://digi-api.com/images/etc/fields/Beast_Empire.png" }],
    releaseDate: "2001",
    descriptions: [],
    skills: [],
    priorEvolutions: [],
    nextEvolutions: [],
  },
  {
    id: 16,
    name: "Veemon X",
    xAntibody: true,
    images: [{ href: "https://digi-api.com/images/digimon/w/Takutoumon(Wrath_Mode).png", transparent: false }],
    levels: [{ id: 5, level: "Ultimate" }],
    types: [{ id: 10, type: "Dragon" }],
    attributes: [{ id: 1, attribute: "Vaccine" }],
    fields: [{ id: 2, field: "Dragon Empire", image: "https://digi-api.com/images/etc/fields/Dragon_Empire.png" }],
    releaseDate: "2001",
    descriptions: [],
    skills: [],
    priorEvolutions: [],
    nextEvolutions: [],
  },
  {
    id: 17,
    name: "Tailmon",
    xAntibody: false,
    images: [{ href: "https://digi-api.com/images/digimon/w/Tailmon.png", transparent: false }],
    levels: [{ id: 4, level: "Champion" }],
    types: [{ id: 19, type: "Beast" }],
    attributes: [{ id: 1, attribute: "Data" }],
    fields: [{ id: 1, field: "Metal Empire", image: "https://digi-api.com/images/etc/fields/Metal_Empire.png" }],
    releaseDate: "1999",
    descriptions: [],
    skills: [],
    priorEvolutions: [],
    nextEvolutions: [],
  },
  {
    id: 18,
    name: "Renamon",
    xAntibody: false,
    images: [{ href: "https://digi-api.com/images/digimon/w/Renamon.png", transparent: false }],
    levels: [{ id: 4, level: "Champion" }],
    types: [{ id: 19, type: "Beast" }],
    attributes: [{ id: 1, attribute: "Data" }],
    fields: [{ id: 1, field: "Metal Empire", image: "https://digi-api.com/images/etc/fields/Metal_Empire.png" }],
    releaseDate: "1999",
    descriptions: [],
    skills: [],
    priorEvolutions: [],
    nextEvolutions: [],
  },
  {
    id: 19,
    name: "Terriermon",
    xAntibody: false,
    images: [{ href: "https://digi-api.com/images/digimon/w/Terriermon.png", transparent: false }],
    levels: [{ id: 4, level: "Champion" }],
    types: [{ id: 18, type: "Mammal" }],
    attributes: [{ id: 1, attribute: "Data" }],
    fields: [{ id: 8, field: "Sky Empire", image: "https://digi-api.com/images/etc/fields/Sky_Empire.png" }],
    releaseDate: "1999",
    descriptions: [],
    skills: [],
    priorEvolutions: [],
    nextEvolutions: [],
  },
  {
    id: 20,
    name: "Impmon",
    xAntibody: false,
    images: [{ href: "https://digi-api.com/images/digimon/w/Impmon.png", transparent: false }],
    levels: [{ id: 4, level: "Champion" }],
    types: [{ id: 21, type: "Demon" }],
    attributes: [{ id: 2, attribute: "Virus" }],
    fields: [{ id: 10, field: "Dark Empire", image: "https://digi-api.com/images/etc/fields/Dark_Empire.png" }],
    releaseDate: "1999",
    descriptions: [],
    skills: [],
    priorEvolutions: [],
    nextEvolutions: [],
  },
]